version: 2
updates:
  # Frontend dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "service: frontend"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "service: frontend"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  # Backend Python dependencies
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "service: backend"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  # Worker Python dependencies
  - package-ecosystem: "pip"
    directory: "/worker"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "service: worker"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  # ASR service dependencies
  - package-ecosystem: "pip"
    directory: "/services/asr"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "service: asr"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  # NLP service dependencies
  - package-ecosystem: "pip"
    directory: "/services/nlp"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "service: nlp"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "infrastructure"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  - package-ecosystem: "docker"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "infrastructure"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  - package-ecosystem: "docker"
    directory: "/services/asr"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "infrastructure"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  - package-ecosystem: "docker"
    directory: "/services/nlp"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "infrastructure"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "ci/cd"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

