version: "3.9"
services:
  redis:
    image: redis:7
    restart: unless-stopped

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: writers
      POSTGRES_USER: writers
      POSTGRES_PASSWORD: writerspass
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    ports: ["9000:9000","9001:9001"]
    volumes:
      - minio:/data
    restart: unless-stopped

  asr:
    build: ./services/asr
    environment:
      WHISPER_MODEL: large-v3
      CUDA_VISIBLE_DEVICES: "0"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    volumes:
      - ./models:/app/models
      - ./data:/app/data
    ports: ["7000:7000"]
    depends_on: [redis]
    restart: unless-stopped

  nlp:
    build: ./services/nlp
    environment:
      REDIS_URL: redis://redis:6379/0
      POSTGRES_DSN: postgresql+psycopg://writers:writerspass@postgres:5432/writers
      S3_ENDPOINT: http://minio:9000
      S3_ACCESS_KEY: ${MINIO_ROOT_USER:-minioadmin}
      S3_SECRET_KEY: ${MINIO_ROOT_PASSWORD:-minioadmin}
      S3_BUCKET: writers
      SUMMARIZER_BACKEND: local
      VLLM_URL: http://vllm:8000/v1
      OPENAI_API_KEY: ""
      ASR_URL: http://asr:7000/transcribe
      EXTERNAL_BASE_URL: http://localhost:8001
    ports: ["8001:8001"]
    depends_on: [redis, postgres, minio, asr]
    restart: unless-stopped

  worker:
    build: ./services/nlp
    command: ["celery","-A","app.celery_app.celery","worker","-Q","default","--concurrency","2","-l","INFO"]
    environment:
      REDIS_URL: redis://redis:6379/0
      POSTGRES_DSN: postgresql+psycopg://writers:writerspass@postgres:5432/writers
      S3_ENDPOINT: http://minio:9000
      S3_ACCESS_KEY: ${MINIO_ROOT_USER:-minioadmin}
      S3_SECRET_KEY: ${MINIO_ROOT_PASSWORD:-minioadmin}
      S3_BUCKET: writers
      SUMMARIZER_BACKEND: local
      VLLM_URL: http://vllm:8000/v1
      OPENAI_API_KEY: ""
      ASR_URL: http://asr:7000/transcribe
      EXTERNAL_BASE_URL: http://nlp:8001
    depends_on: [nlp]
    restart: unless-stopped

  # اختیاری: LLM محلی
  vllm:
    image: vllm/vllm-openai:latest
    command: ["--model","meta-llama/Meta-Llama-3.1-8B-Instruct"]
    environment:
      VLLM_WORKER_USE_NCCL: "0"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    ports: ["8000:8000"]
    restart: unless-stopped

volumes:
  pgdata:
  minio:
