# Prometheus configuration for Writers application
# Collects metrics from FastAPI, Nginx, PostgreSQL, Redis, and system

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'writers-production'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'localhost:9093'

# Load rules
rule_files:
  - 'alerts/*.yml'

# Scrape configurations
scrape_configs:
  # FastAPI application metrics
  - job_name: 'fastapi'
    static_configs:
      - targets: ['localhost:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Nginx metrics (requires nginx-prometheus-exporter)
  - job_name: 'nginx'
    static_configs:
      - targets: ['localhost:9113']
    scrape_interval: 10s

  # PostgreSQL metrics (requires postgres_exporter)
  - job_name: 'postgresql'
    static_configs:
      - targets: ['localhost:9187']
    scrape_interval: 30s

  # Redis metrics (requires redis_exporter)
  - job_name: 'redis'
    static_configs:
      - targets: ['localhost:9121']
    scrape_interval: 10s

  # Node exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']
    scrape_interval: 15s

  # NVIDIA GPU metrics (requires nvidia_gpu_exporter)
  - job_name: 'nvidia_gpu'
    static_configs:
      - targets: ['localhost:9835']
    scrape_interval: 10s

  # Celery worker metrics (if prometheus integration is added)
  - job_name: 'celery'
    static_configs:
      - targets: ['localhost:9808']
    scrape_interval: 15s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
