blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/yourusername/writers-notetaker/tree/main/docs
    about: Check our documentation for guides and troubleshooting
  - name: Discussions
    url: https://github.com/yourusername/writers-notetaker/discussions
    about: Ask questions and discuss ideas with the community

